FROM registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1

# Configure APT proxy for internal use during setup
ARG APT_PROXY=192.168.76.5:3142
RUN echo "Acquire::http::Proxy \"http:///\";" > /etc/apt/apt.conf.d/01proxy

# Use archived repos for Buster
RUN echo 'deb http://archive.debian.org/debian buster main' > /etc/apt/sources.list &&     echo 'deb http://archive.debian.org/debian-security buster/updates main' >> /etc/apt/sources.list

RUN apt-get update && apt-get install -qy     bash     git     jq     && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENTRYPOINT ["/bin/bash"]
